version: '3.1'

services:
    redis:
        image: redis:alpine
        container_name: SynapseFlow-redis
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        networks:
            - SynapseFlow-net

    SynapseFlow:
        container_name: SynapseFlow-main
        build:
            context: .. # Build using the Dockerfile in the root directory
            dockerfile: docker/Dockerfile
        ports:
            - '${PORT}:${PORT}'
        volumes:
            # Mount local .SynapseFlow to container's default location
            - ../.SynapseFlow:/root/.SynapseFlow
        environment:
            # --- Essential SynapseFlow Vars ---
            - PORT=${PORT:-3000}
            - DATABASE_PATH=/root/.SynapseFlow
            - SECRETKEY_PATH=/root/.SynapseFlow
            - LOG_PATH=/root/.SynapseFlow/logs
            - BLOB_STORAGE_PATH=/root/.SynapseFlow/storage
            # --- Queue Vars (Main Instance) ---
            - MODE=queue
            - QUEUE_NAME=SynapseFlow-queue # Ensure this matches worker
            - REDIS_URL=redis://redis:6379 # Use service name 'redis'
        depends_on:
            - redis
        networks:
            - SynapseFlow-net

    SynapseFlow-worker:
        container_name: SynapseFlow-worker
        build:
            context: .. # Build context is still the root
            dockerfile: docker/worker/Dockerfile # Ensure this path is correct
        volumes:
            # Mount same local .SynapseFlow to worker
            - ../.SynapseFlow:/root/.SynapseFlow
        environment:
            # --- Essential SynapseFlow Vars ---
            - WORKER_PORT=${WORKER_PORT:-5566} # Port for worker healthcheck
            - DATABASE_PATH=/root/.SynapseFlow
            - SECRETKEY_PATH=/root/.SynapseFlow
            - LOG_PATH=/root/.SynapseFlow/logs
            - BLOB_STORAGE_PATH=/root/.SynapseFlow/storage
            # --- Queue Vars (Main Instance) ---
            - MODE=queue
            - QUEUE_NAME=SynapseFlow-queue # Ensure this matches worker
            - REDIS_URL=redis://redis:6379 # Use service name 'redis'
        depends_on:
            - redis
            - SynapseFlow
        networks:
            - SynapseFlow-net

volumes:
    redis_data:
        driver: local

networks:
    SynapseFlow-net:
        driver: bridge
